#!/bin/bash
# post-compact-hook.sh — Re-injeta contexto essencial após compaction
#
# Uso: SessionStart hook com matcher "compact"
# Claude Code invoca este script com JSON no stdin quando a sessão
# foi iniciada após um /compact. O script emite additionalContext
# com STATE.md (if fresh), domain map e lembrete do CLAUDE.md.
#
# STATE.md é um session buffer gerado pelo /bootstrap — não um cache
# persistido. Se está stale (>24h), não re-injeta dados velhos.

INPUT=$(cat)
CWD=$(echo "$INPUT" | jq -r '.cwd // "."')

CONTEXT=""

# --- STATE.md ---
# Re-inject only if fresh (generated in this session, <24h old)
STATE_FILE="${CWD}/.claude/state/STATE.md"
if [ -f "$STATE_FILE" ]; then
  # Check timestamp in header: <!-- Generated by /bootstrap at YYYY-MM-DDTHH:MM:SS -->
  STATE_TIMESTAMP=$(grep -oP '(?<=Generated by /bootstrap at )\S+' "$STATE_FILE" 2>/dev/null)
  INJECT_STATE=true

  if [ -n "$STATE_TIMESTAMP" ]; then
    # Compare with current time — reject if >24h old
    STATE_EPOCH=$(date -d "$STATE_TIMESTAMP" +%s 2>/dev/null || date -j -f "%Y-%m-%dT%H:%M:%S" "$STATE_TIMESTAMP" +%s 2>/dev/null)
    NOW_EPOCH=$(date +%s)
    if [ -n "$STATE_EPOCH" ]; then
      AGE=$(( NOW_EPOCH - STATE_EPOCH ))
      if [ "$AGE" -gt 86400 ]; then
        INJECT_STATE=false
      fi
    fi
  fi

  if [ "$INJECT_STATE" = true ]; then
    STATE_CONTENT=$(cat "$STATE_FILE")
    CONTEXT="${CONTEXT}## Project State (re-injected after compaction)

${STATE_CONTENT}

"
  else
    CONTEXT="${CONTEXT}## Project State

STATE.md is stale (>24h old). Run /bootstrap to refresh session context.

"
  fi
fi

# --- Domain map ---
# Index de documentação do projeto — orientação rápida de onde fica o quê
DOMAIN_INDEX="${CWD}/.claude/docs/index.md"
if [ -f "$DOMAIN_INDEX" ]; then
  INDEX_CONTENT=$(cat "$DOMAIN_INDEX")
  CONTEXT="${CONTEXT}## Domain Map

${INDEX_CONTENT}

"
fi

# --- CLAUDE.md reminder ---
# Não re-injeta o conteúdo completo (Claude Code já o carrega), apenas
# emite um lembrete explícito para garantir que seja relido após compaction
CLAUDE_MD="${CWD}/CLAUDE.md"
if [ -f "$CLAUDE_MD" ]; then
  CONTEXT="${CONTEXT}## Context reminder

Re-read CLAUDE.md for full project context — it was loaded before compaction
and must be consulted again before acting.

"
fi

# Se não há nada a injetar, sair silenciosamente
if [ -z "$CONTEXT" ]; then
  exit 0
fi

# Emite o contexto como additionalContext para o SessionStart hook
CONTEXT="${CONTEXT}---
Context compaction detected. The above was re-injected to restore session continuity."

jq -n --arg ctx "$CONTEXT" '{
  "hookSpecificOutput": {
    "hookEventName": "SessionStart",
    "additionalContext": $ctx
  }
}'

exit 0
